// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShootersTrackingSystem.Database;

#nullable disable

namespace ShootersTrackingSystem.Migrations
{
    [DbContext(typeof(ShootersDbContext))]
    partial class ShootersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShootersTrackingSystem.Model.Entities.Attempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Score")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WeaponId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Attempts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3242),
                            Score = 100L,
                            UserId = 3,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3259),
                            Score = 90L,
                            UserId = 3,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3273),
                            Score = 60L,
                            UserId = 3,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3287),
                            Score = 50L,
                            UserId = 3,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3301),
                            Score = 60L,
                            UserId = 3,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 6,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3316),
                            Score = 100L,
                            UserId = 3,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 7,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3375),
                            Score = 90L,
                            UserId = 3,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 8,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3389),
                            Score = 70L,
                            UserId = 3,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 9,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3402),
                            Score = 70L,
                            UserId = 3,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 10,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3417),
                            Score = 60L,
                            UserId = 3,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 11,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3429),
                            Score = 100L,
                            UserId = 4,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 12,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3444),
                            Score = 90L,
                            UserId = 4,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 13,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3457),
                            Score = 90L,
                            UserId = 4,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 14,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3470),
                            Score = 90L,
                            UserId = 4,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 15,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3484),
                            Score = 90L,
                            UserId = 4,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 16,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3497),
                            Score = 90L,
                            UserId = 4,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 17,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3510),
                            Score = 90L,
                            UserId = 4,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 18,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3525),
                            Score = 80L,
                            UserId = 4,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 19,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3537),
                            Score = 80L,
                            UserId = 4,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 20,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3551),
                            Score = 70L,
                            UserId = 4,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 21,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3565),
                            Score = 90L,
                            UserId = 5,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 22,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3578),
                            Score = 90L,
                            UserId = 5,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 23,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3591),
                            Score = 90L,
                            UserId = 5,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 24,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3626),
                            Score = 90L,
                            UserId = 5,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 25,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3639),
                            Score = 90L,
                            UserId = 5,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 26,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3652),
                            Score = 90L,
                            UserId = 5,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 27,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3666),
                            Score = 80L,
                            UserId = 5,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 28,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3679),
                            Score = 80L,
                            UserId = 5,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 29,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3692),
                            Score = 80L,
                            UserId = 5,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 30,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3705),
                            Score = 80L,
                            UserId = 5,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 31,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3718),
                            Score = 20L,
                            UserId = 3,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 32,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3731),
                            Score = 30L,
                            UserId = 3,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 33,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3744),
                            Score = 30L,
                            UserId = 3,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 34,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3758),
                            Score = 20L,
                            UserId = 3,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 35,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3772),
                            Score = 60L,
                            UserId = 3,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 36,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3785),
                            Score = 70L,
                            UserId = 3,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 37,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3798),
                            Score = 30L,
                            UserId = 3,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 38,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3810),
                            Score = 20L,
                            UserId = 3,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 39,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3824),
                            Score = 40L,
                            UserId = 3,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 40,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3838),
                            Score = 40L,
                            UserId = 3,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 41,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3851),
                            Score = 50L,
                            UserId = 4,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 42,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3864),
                            Score = 50L,
                            UserId = 4,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 43,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3878),
                            Score = 50L,
                            UserId = 4,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 44,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3891),
                            Score = 60L,
                            UserId = 4,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 45,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3904),
                            Score = 60L,
                            UserId = 4,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 46,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3917),
                            Score = 70L,
                            UserId = 4,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 47,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3930),
                            Score = 80L,
                            UserId = 4,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 48,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3943),
                            Score = 80L,
                            UserId = 4,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 49,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3955),
                            Score = 80L,
                            UserId = 4,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 50,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3968),
                            Score = 20L,
                            UserId = 4,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 51,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(3981),
                            Score = 100L,
                            UserId = 5,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 52,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4017),
                            Score = 100L,
                            UserId = 5,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 53,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4030),
                            Score = 100L,
                            UserId = 5,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 54,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4043),
                            Score = 20L,
                            UserId = 5,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 55,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4056),
                            Score = 20L,
                            UserId = 5,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 56,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4069),
                            Score = 30L,
                            UserId = 5,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 57,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4082),
                            Score = 40L,
                            UserId = 5,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 58,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4094),
                            Score = 50L,
                            UserId = 5,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 59,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4108),
                            Score = 60L,
                            UserId = 5,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 60,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4121),
                            Score = 70L,
                            UserId = 5,
                            WeaponId = 2
                        },
                        new
                        {
                            Id = 61,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4134),
                            Score = 20L,
                            UserId = 3,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 62,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4148),
                            Score = 40L,
                            UserId = 3,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 63,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4160),
                            Score = 60L,
                            UserId = 3,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 64,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4173),
                            Score = 70L,
                            UserId = 3,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 65,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4186),
                            Score = 80L,
                            UserId = 3,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 66,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4200),
                            Score = 80L,
                            UserId = 3,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 67,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4213),
                            Score = 80L,
                            UserId = 3,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 68,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4226),
                            Score = 80L,
                            UserId = 3,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 69,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4240),
                            Score = 60L,
                            UserId = 3,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 70,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4253),
                            Score = 30L,
                            UserId = 3,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 71,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4265),
                            Score = 30L,
                            UserId = 4,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 72,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4278),
                            Score = 100L,
                            UserId = 4,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 73,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4291),
                            Score = 90L,
                            UserId = 4,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 74,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4304),
                            Score = 100L,
                            UserId = 4,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 75,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4317),
                            Score = 100L,
                            UserId = 4,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 76,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4330),
                            Score = 90L,
                            UserId = 4,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 77,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4369),
                            Score = 20L,
                            UserId = 4,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 78,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4382),
                            Score = 60L,
                            UserId = 4,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 79,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4395),
                            Score = 70L,
                            UserId = 4,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 80,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4408),
                            Score = 80L,
                            UserId = 4,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 81,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4421),
                            Score = 90L,
                            UserId = 5,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 82,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4435),
                            Score = 90L,
                            UserId = 5,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 83,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4447),
                            Score = 90L,
                            UserId = 5,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 84,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4460),
                            Score = 80L,
                            UserId = 5,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 85,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4473),
                            Score = 80L,
                            UserId = 5,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 86,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4486),
                            Score = 80L,
                            UserId = 5,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 87,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4499),
                            Score = 70L,
                            UserId = 5,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 88,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4512),
                            Score = 70L,
                            UserId = 5,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 89,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4525),
                            Score = 70L,
                            UserId = 5,
                            WeaponId = 3
                        },
                        new
                        {
                            Id = 90,
                            DateTime = new DateTime(2024, 11, 23, 22, 59, 49, 22, DateTimeKind.Utc).AddTicks(4539),
                            Score = 60L,
                            UserId = 5,
                            WeaponId = 3
                        });
                });

            modelBuilder.Entity("ShootersTrackingSystem.Model.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            Password = "mGyd58jTJYJSftGdmF8p/w==$CSSN/KvfydtzYHbK47N3tufiZ72ka3UKD9lbNTwNe7c=",
                            UserRoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Instructor",
                            Password = "6J8GMK/woJ7lepQ57xBAOg==$T4+RE2fJQOWMTwFft7fz+bLL4+STjR07+XWrJcN/uWk=",
                            UserRoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Client1",
                            Password = "xEK49XWDwgAjSF1bh3pbLA==$q8I1YPTEl/YBoFCVR3L8JS8ubC2bXluXcU5fRKAv4gQ=",
                            UserRoleId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Client2",
                            Password = "xEK49XWDwgAjSF1bh3pbLA==$q8I1YPTEl/YBoFCVR3L8JS8ubC2bXluXcU5fRKAv4gQ=",
                            UserRoleId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Client3",
                            Password = "xEK49XWDwgAjSF1bh3pbLA==$q8I1YPTEl/YBoFCVR3L8JS8ubC2bXluXcU5fRKAv4gQ=",
                            UserRoleId = 3
                        });
                });

            modelBuilder.Entity("ShootersTrackingSystem.Model.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Instructor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Client"
                        });
                });

            modelBuilder.Entity("ShootersTrackingSystem.Model.Entities.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeaponTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeaponTypeId");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ПМ",
                            WeaponTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "АК-74",
                            WeaponTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Сайга-12",
                            WeaponTypeId = 3
                        });
                });

            modelBuilder.Entity("ShootersTrackingSystem.Model.Entities.WeaponType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WeaponTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pistol"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rifle"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shotgun"
                        });
                });

            modelBuilder.Entity("ShootersTrackingSystem.Model.Entities.Attempt", b =>
                {
                    b.HasOne("ShootersTrackingSystem.Model.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShootersTrackingSystem.Model.Entities.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("ShootersTrackingSystem.Model.Entities.User", b =>
                {
                    b.HasOne("ShootersTrackingSystem.Model.Entities.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("ShootersTrackingSystem.Model.Entities.Weapon", b =>
                {
                    b.HasOne("ShootersTrackingSystem.Model.Entities.WeaponType", "WeaponType")
                        .WithMany("Weapons")
                        .HasForeignKey("WeaponTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("ShootersTrackingSystem.Model.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShootersTrackingSystem.Model.Entities.WeaponType", b =>
                {
                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
